### ISSUE TITLE
Crash on Server for 1.12.2

### ISSUE THREAD

**Issue by Zenith08** [Zenith08/Model-Trains-Mod#2]
Originally posted by Kreezxil:

> Issue: 1.12 - 1.2.1 crashes dedicated server Forge 1.12.2 build 2509

> Notes:

> on startup while looking for client side classes

> crash report:

> https://gist.github.com/4f06cf922c227bb0c431946fe31cf72f

> fml server latest:

> https://gist.github.com/1927d5535694183035b7ae21aa178a5d

**Comment by SDUBZ** [comment]
same here 

> java.lang.NoClassDefFoundError: org/lwjgl/util/vector/Vector3f at me.kk47.ueri.util.RenderTransform.(RenderTransform.java:21) ~[RenderTransform.class:?] at me.kk47.ueri.util.RenderTransform.(RenderTransform.java:9) ~[RenderTransform.class:?] at me.kk47.modeltrains.items.trains.ItemToyTrain.(ItemToyTrain.java:17) ~[ItemToyTrain.class:?] at me.kk47.modeltrains.items.ModItems.registerItems(ModItems.java:47) ~[ModItems.class:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_858_ModItems_registerItems_Register.invoke(.dynamic) ~[?:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?] at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143) ~[EventBus$1.class:?] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?] at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:739) ~[GameData.class:?] at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603) ~[Loader.class:?] at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?] at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) ~[FMLCommonHandler.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]Caused by: java.lang.ClassNotFoundException: org.lwjgl.util.vector.Vector3f at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_141] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_141] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141] at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141] ... 15 more

**Comment by Zenith08** [comment]
I have a (Hopefully) fix but right now Minecraft Forge wont let me test it easily. If you build the mod from this github repository, you might get results but to be honest I don't have the option to test it. A full release version will be available once I can confirm it works.

**Comment by Zenith08** [comment]
I have finally tested and found the fix in version 1.2.2 to be successful.
Let me know if anyone experiences any further issues.
-Zenith
